# Generated by Django 4.2.6 on 2024-02-10 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='watchlist',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='readlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
