# Generated by Django 4.2.6 on 2024-02-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_readlist_watchlist_alter_readlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readlist',
        ),
    ]
