# Generated by Django 4.2.6 on 2024-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
