# Generated by Django 4.2.6 on 2024-01-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
