# Generated by Django 4.2.6 on 2024-02-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_hold',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=0, max_length=8000),
        ),
        migrations.AddField(
            model_name='comment',
            name='hold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='article.comment'),
        ),
    ]
