# Generated by Django 4.2.6 on 2024-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_comment_comment_hold_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=True, max_length=8000),
        ),
    ]
