# Generated by Django 4.2.6 on 2024-02-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_watchlistitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='content',
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
