# Generated by Django 4.2.6 on 2024-02-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_remove_watchlistitem_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
