# Generated by Django 4.2.6 on 2024-02-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_watchlistitem_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
