# Generated by Django 4.2.6 on 2024-02-12 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0021_alter_watchlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'article')},
        ),
    ]
