# Generated by Django 4.2.6 on 2024-02-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_alter_watchlistitem_article_alter_watchlistitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='pub_date',
        ),
    ]
