# Generated by Django 4.2.6 on 2024-02-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_remove_watchlistitem_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
